typography_spectrum: 0.9715996913146228
content_rating:
  adult: true
color:
  brandStrength: 0.8372856858186424
  lightness: 0.4306266226340085
  saturation: 0.2780590574257076
  rhythmicContrast: 0.2816225260030478
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.3752022422850132
author:
  name: Vaughn D. Taylor
  email: vaughn.taylor@gmail.com
  url: 'http://vaughn.fyi'
name: Vaughn D. Taylor
